### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by linoor** [linoor/MecatroMouve#1]
Maybe we should use this shit to manage tasks for everyone?

**Comment by linoor** [comment]
I mean that it would be a good idea to use the github task/issues system to track the tasks.

**Comment by erichoco** [comment]
Yeah but ain't too familiar with it...

**Comment by alreadytaikeune** [comment]
Da fuck u talkin' 'bout

**Comment by erichoco** [comment]
I mean it's a good idea but I am not familiar with github issue. So... hope it works well ;)

**Comment by linoor** [comment]
You can easily see all the tasks here and who is assigned so I think it's a little bit clearer, don't you think?

**Comment by erichoco** [comment]
oh so hashtagging numbers will make a reference of the issue
i didn't intend for that tho

**Comment by erichoco** [comment]
btw how do you make an issue a PR?

**Comment by linoor** [comment]
Nice I didn't know that :p What is PR?

**Comment by linoor** [comment]
Never mind, I got it :P

**Comment by erichoco** [comment]
> PR === pull request
> ---------------- _erichoco_ (1992- )

**Comment by erichoco** [comment]
so issue and PR are different still i guess
i was confused cuz you had an issue and a PR for `feature/magnetometre`. i thought they're the same.

**Comment by linoor** [comment]
Yeah, you do a pull request when you finish writing the code and want someone to check if it look fine. Then you can merge it automatically into dev or master. I should've just made a pull request I guess.
